[tools]
# Programming Languages
go = "latest"
node = "latest"
python = "latest"

# IaC
terraform = "latest"

# Tools
fzf = "latest"
gcloud = "latest"
golangci-lint = "latest"
kubectl = "latest"
kubectx = "latest"
kubens = "latest"
pinact = "latest"
pnpm = "latest"
bun = "latest"
